openapi: 3.0.3
info:
  title: Swagger Pricing - OpenAPI 3.0
  description: |-
  version: 2.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: pricing
    description: Pricing Api
paths:
  /api/prices:
    get:
      summary: Get price
      operationId: getPrice
      tags:
        - pricing
      parameters:
        - in: query
          name: brandId
          schema:
            type: integer
          required: true
        - in: query
          name: productId
          schema:
            type: integer
          required: true
        - in: query
          name: date
          schema:
            type: string
            format: date-time
          required: true
      responses:
        '200':
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '404':
          description: Price not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Bad request, missing parameters!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'


components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
        brandId:
          type: integer
        priceList:
          type: integer
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        price:
          type: number
          format: double

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        status:
          type: integer
        message:
          type: string

