version: '3.8'

services:
  postgres:
    image: postgres:13.5
    container_name: inditex-db
    restart: always
    environment:
      POSTGRES_DB: inditex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d


